# Generated by Django 3.2.8 on 2023-06-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochetwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_name',
            field=models.CharField(max_length=50),
        ),
    ]
