# Generated by Django 3.2.8 on 2023-06-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochetwork', '0002_alter_entry_entry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_template',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
