# Generated by Django 3.2.8 on 2023-06-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochetwork', '0003_auto_20230617_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_template',
            field=models.TextField(default=''),
        ),
    ]
