# Generated by Django 3.2.8 on 2023-06-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochetwork', '0005_alter_entry_entry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_image',
            field=models.ImageField(default=None, upload_to='images/<property object at 0x7f8441280f40>/'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_template',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
