# Generated by Django 3.2.8 on 2023-06-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochetwork', '0006_auto_20230619_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
